### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by AliakseiSakolin**

### CODE REVIEW

**Comment by maksczyk** [comment]
lmao boat

**Comment by AliakseiSakolin** [comment]
nerd emoji

**Comment by AliakseiSakolin** [comment]
lol

**Comment by AliakseiSakolin** [comment]
🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓
Landon144DorkGIF

**Pull request merged**
